#!/bin/bash

set -euo pipefail

TOKEN=$(printenv ${BUILDKITE_PLUGIN_SLACK_REPORTER_TOKEN:-"SLACK_TOKEN"})
CHANNEL=$(printenv ${BUILDKITE_PLUGIN_SLACK_REPORTER_CHANNEL:-"SLACK_CHANNEL"})

COLOR="good"
if [ ${BUILDKITE_COMMAND_EXIT_STATUS} -ne 0 ]; then
  COLOR="danger"
fi

JSON=$(curl -sL -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -d "{\
    \"channel\": \"${CHANNEL}\", \"ts\": \"${SLACK_TS}\",\
    \"attachments\": [{\
      \"color\": \"${COLOR}\",\
      \"fields\": [\
        {\"short\": true, \"title\": \"Repo\", \"value\": \"${BUILDKITE_REPO}\"},\
        {\"short\": true, \"title\": \"Branch\", \"value\": \"${BUILDKITE_BRANCH}\"},\
        {\"short\": true, \"title\": \"Build\", \"value\": \"<${BUILDKITE_BUILD_URL} | ${BUILDKITE_BUILD_ID}>\"},\
        {\"short\": true, \"title\": \"Job\", \"value\": \"${BUILDKITE_LABEL}\"}\
      ]\
    }]\
  }" https://slack.com/api/chat.update)
