#!/bin/bash

set -euo pipefail

TOKEN=$(printenv ${BUILDKITE_PLUGIN_SLACK_REPORTER_TOKEN:-"SLACK_TOKEN"})
CHANNEL=$(printenv ${BUILDKITE_PLUGIN_SLACK_REPORTER_CHANNEL:-"SLACK_CHANNEL"})

JSON=$(curl -sL -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -d "{\
    \"channel\": \"${CHANNEL}\",\
    \"attachments\": [{\
      \"color\": \"warning\",\
      \"fields\": [\
        {\"short\": true, \"title\": \"Repo\", \"value\": \"${BUILDKITE_REPO}\"},\
        {\"short\": true, \"title\": \"Branch\", \"value\": \"${BUILDKITE_BRANCH}\"},\
        {\"short\": true, \"title\": \"Build\", \"value\": \"<${BUILDKITE_BUILD_URL} | ${BUILDKITE_BUILD_ID}>\"},\
        {\"short\": true, \"title\": \"Job\", \"value\": \"${BUILDKITE_LABEL}\"}\
      ]\
    }]\
  }" https://slack.com/api/chat.postMessage)

export SLACK_TS=$(echo ${JSON} | jq -r .ts)
